### ISSUE TITLE
Weapon systems with Hot dont work for Vehicle/Crawler type Actors

### ISSUE THREAD

**Issue by LottVanfield** [Stexinator/salvage-union-combat-automation#4]
When clicking the attack button from a System mounted on a Vehicle or Crawler type Actor nothing happens.

In the console the following error is generated:
TypeError: Cannot read properties of undefined (reading 'value')
    at SalvageUnionCombatAutomationHeat.handleHeat (heat.js:8:47)
    at SalvageUnionCombatAutomationWeapons.handleTraits (weapons.js:90:58)
    at SalvageUnionCombatAutomationWeapons.handleAttackRollButton (weapons.js:55:23)

**Comment by Stexinator** [comment]
fixed
