### ISSUE TITLE
Clicking dice icon on actor sheet not triggering Dice So Nice

### ISSUE THREAD

**Issue by tak5haka** [Stexinator/salvage-union-combat-automation#6]
When clicking the dice icon on the actor sheet, the table is rolled and chat result is normal, however Dice So Nice is not being triggered even though this is a dice roll.

Foundry version 12 Stable - Build 331
Salvage Union (Unofficial) v1.2.2
Salvage Union Combat Automation Module v0.0.26
Dice So Nice v5.1.3

Console error: 
```
foundry-esm.js:4621 Error: CONST.CHAT_MESSAGE_STYLES.ROLL is deprecated in favor of defining rolls directly in ChatMessage#rolls
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Object.get (foundry-esm.js:2505:23)
    at SalvageUnionCombatAutomationWeapons.handleAttackRoll (weapons.js:88:48)
```

**Comment by tak5haka** [comment]
If the following is added to Line 86 on `weapons.js` (after `roll: result.roll,`) it seems to work again (at least for me and just for a weapon attack, not for abilities):

`rolls: [result.roll],`
